require:
  - rubocop-rails
  - rubocop-performance
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
